# coding: utf-8

"""
    Criação de Contas

    API de Criação de Contas.  # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: cadastro_api@orama.com.br
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import openapi_client
from openapi_client.api.developers_api import DevelopersApi  # noqa: E501
from openapi_client.rest import ApiException


class TestDevelopersApi(unittest.TestCase):
    """DevelopersApi unit test stubs"""

    def setUp(self):
        self.api = openapi_client.api.developers_api.DevelopersApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_perfil_get(self):
        """Test case for perfil_get

        Retorna uma lista composta por objetos do tipo perfil  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
