# coding: utf-8

"""
    Criação de Contas

    API de Criação de Contas.  # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: cadastro_api@orama.com.br
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import cadastro_orama
from cadastro_orama.models.front_end_step import FrontEndStep  # noqa: E501
from cadastro_orama.rest import ApiException


class TestFrontEndStep(unittest.TestCase):
    """FrontEndStep unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testFrontEndStep(self):
        """Test FrontEndStep"""
        # FIXME: construct object with mandatory attributes with example values
        # model = cadastro_orama.models.front_end_step.FrontEndStep()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
