# coding: utf-8

"""
    Criação de Contas

    API de Criação de Contas.  # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: cadastro_api@orama.com.br
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import openapi_client
from openapi_client.models.conta_bancaria import ContaBancaria  # noqa: E501
from openapi_client.rest import ApiException


class TestContaBancaria(unittest.TestCase):
    """ContaBancaria unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testContaBancaria(self):
        """Test ContaBancaria"""
        # FIXME: construct object with mandatory attributes with example values
        # model = openapi_client.models.conta_bancaria.ContaBancaria()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
