# coding: utf-8

"""
    Criação de Contas

    API de Criação de Contas.  # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: cadastro_api@orama.com.br
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import openapi_client
from openapi_client.api.users_api import UsersApi  # noqa: E501
from openapi_client.rest import ApiException


class TestUsersApi(unittest.TestCase):
    """UsersApi unit test stubs"""

    def setUp(self):
        self.api = openapi_client.api.users_api.UsersApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_account_autenticacao_post(self):
        """Test case for account_autenticacao_post

        Autentica um usuário que ainda não é cliente.  # noqa: E501
        """
        pass

    def test_account_documento_confirmacao_get(self):
        """Test case for account_documento_confirmacao_get

        Consulta o status de confirmação do documento que foi submetido  # noqa: E501
        """
        pass

    def test_account_documento_put(self):
        """Test case for account_documento_put

        Anexa ou atualiza documento para conferencia de autenticidade do perfil.  # noqa: E501
        """
        pass

    def test_account_identificacao_post(self):
        """Test case for account_identificacao_post

        Cria um login para usuário.  # noqa: E501
        """
        pass

    def test_account_perfil_aprovacao_get(self):
        """Test case for account_perfil_aprovacao_get

        Retorna o estado de aprovação de um perfil  # noqa: E501
        """
        pass

    def test_account_perfil_celular_autenticacao_confirmacao_get(self):
        """Test case for account_perfil_celular_autenticacao_confirmacao_get

        Estado atual de confirmação do celular  # noqa: E501
        """
        pass

    def test_account_perfil_celular_autenticacao_post(self):
        """Test case for account_perfil_celular_autenticacao_post

        Gera um código para iniciar o processo de validação do número do celular  # noqa: E501
        """
        pass

    def test_account_perfil_celular_confirmacao_post(self):
        """Test case for account_perfil_celular_confirmacao_post

        Confirma o numero de celular, concluindo a validação  # noqa: E501
        """
        pass

    def test_account_perfil_email_autenticacao_confirmacao_get(self):
        """Test case for account_perfil_email_autenticacao_confirmacao_get

        Estado atual de confirmação do email  # noqa: E501
        """
        pass

    def test_account_perfil_email_autenticacao_post(self):
        """Test case for account_perfil_email_autenticacao_post

        Gera um código para iniciar o processo de validação do email  # noqa: E501
        """
        pass

    def test_account_perfil_email_confirmacao_post(self):
        """Test case for account_perfil_email_confirmacao_post

        Confirma o email, concluindo a validação  # noqa: E501
        """
        pass

    def test_account_perfil_get(self):
        """Test case for account_perfil_get

        Retorna o perfil de um usuário que ainda não foi transformado em cliente.  # noqa: E501
        """
        pass

    def test_account_perfil_post(self):
        """Test case for account_perfil_post

        Submete o perfil de usuário associado a um login para ser criado como cliente.  # noqa: E501
        """
        pass

    def test_account_perfil_put(self):
        """Test case for account_perfil_put

        Atualiza perfil para criação de conta.  # noqa: E501
        """
        pass

    def test_account_perfil_submetido_get(self):
        """Test case for account_perfil_submetido_get

        Retorna o estado de submissão de um perfil  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
