# coding: utf-8

"""
    Criação de Contas

    API de Criação de Contas.  # noqa: E501

    The version of the OpenAPI document: 2.0
    Contact: cadastro_api@orama.com.br
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import cadastro_orama
from cadastro_orama.models.assinatura_eletronica import AssinaturaEletronica  # noqa: E501
from cadastro_orama.rest import ApiException

class TestAssinaturaEletronica(unittest.TestCase):
    """AssinaturaEletronica unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test AssinaturaEletronica
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = cadastro_orama.models.assinatura_eletronica.AssinaturaEletronica()  # noqa: E501
        if include_optional :
            return AssinaturaEletronica(
                assinatura_eletronica = 'AE979400051'
            )
        else :
            return AssinaturaEletronica(
        )

    def testAssinaturaEletronica(self):
        """Test AssinaturaEletronica"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
