# coding: utf-8

"""
    Criação de Contas

    API de Criação de Contas.  # noqa: E501

    The version of the OpenAPI document: 2.0
    Contact: cadastro_api@orama.com.br
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import re  # noqa: F401

# python 2 and python 3 compatibility library
import six

from cadastro_orama.api_client import ApiClient
from cadastro_orama.exceptions import (
    ApiTypeError,
    ApiValueError
)


class DevelopersApi(object):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    def __init__(self, api_client=None):
        if api_client is None:
            api_client = ApiClient()
        self.api_client = api_client

    def account_identificacao_parceiro_post(self, login_senha_objeto, **kwargs):  # noqa: E501
        """Cria um login para usuário.  # noqa: E501

        Cria um novo login que será usado para acesso ao sistema.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.account_identificacao_parceiro_post(login_senha_objeto, async_req=True)
        >>> result = thread.get()

        :param async_req bool: execute request asynchronously
        :param LoginSenhaObjeto login_senha_objeto: Dados para criação do login (required)
        :param _preload_content: if False, the urllib3.HTTPResponse object will
                                 be returned without reading/decoding response
                                 data. Default is True.
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :return: LoginCriado
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        return self.account_identificacao_parceiro_post_with_http_info(login_senha_objeto, **kwargs)  # noqa: E501

    def account_identificacao_parceiro_post_with_http_info(self, login_senha_objeto, **kwargs):  # noqa: E501
        """Cria um login para usuário.  # noqa: E501

        Cria um novo login que será usado para acesso ao sistema.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.account_identificacao_parceiro_post_with_http_info(login_senha_objeto, async_req=True)
        >>> result = thread.get()

        :param async_req bool: execute request asynchronously
        :param LoginSenhaObjeto login_senha_objeto: Dados para criação do login (required)
        :param _return_http_data_only: response data without head status code
                                       and headers
        :param _preload_content: if False, the urllib3.HTTPResponse object will
                                 be returned without reading/decoding response
                                 data. Default is True.
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :return: tuple(LoginCriado, status_code(int), headers(HTTPHeaderDict))
                 If the method is called asynchronously,
                 returns the request thread.
        """

        local_var_params = locals()

        all_params = ['login_senha_objeto']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        for key, val in six.iteritems(local_var_params['kwargs']):
            if key not in all_params:
                raise ApiTypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method account_identificacao_parceiro_post" % key
                )
            local_var_params[key] = val
        del local_var_params['kwargs']
        # verify the required parameter 'login_senha_objeto' is set
        if self.api_client.client_side_validation and ('login_senha_objeto' not in local_var_params or  # noqa: E501
                                                        local_var_params['login_senha_objeto'] is None):  # noqa: E501
            raise ApiValueError("Missing the required parameter `login_senha_objeto` when calling `account_identificacao_parceiro_post`")  # noqa: E501

        collection_formats = {}

        path_params = {}

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        if 'login_senha_objeto' in local_var_params:
            body_params = local_var_params['login_senha_objeto']
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['Api-Key']  # noqa: E501

        return self.api_client.call_api(
            '/identificacao-parceiro/', 'POST',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='LoginCriado',  # noqa: E501
            auth_settings=auth_settings,
            async_req=local_var_params.get('async_req'),
            _return_http_data_only=local_var_params.get('_return_http_data_only'),  # noqa: E501
            _preload_content=local_var_params.get('_preload_content', True),
            _request_timeout=local_var_params.get('_request_timeout'),
            collection_formats=collection_formats)
